### ISSUE TITLE
Compilation error when using Envoc.Stripe.Terminal.Android v3.2.1.2

### ISSUE THREAD

**Issue by christhwaites** [Envoc/envoc-stripe-binding#5]
Hi There,

I'm trying to use the stripe terminal bindings for android in my .NETCore android project, and struggling a little bit...

If I create a new .NET 7.0 Android Application in Visual Studio, and then just add a nuget reference to Envoc.Stripe.Terminal.Android v2.19.3 and build... all is good. It builds as expected.

BUT... if I use the latest stable version (3.2.1.2) and try to build, I get the following errors (as well as duplicates of these errors):

```
1>AndroidApp3 -> D:\Stuff\NETStripeAndroid\AndroidApp3\AndroidApp3\bin\Debug\net7.0-android33.0\AndroidApp3.dll
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): javac.exe error JAVAC0000:  error: package com.google.android.gms.common.api.GoogleApiClient does not exist
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): javac.exe error JAVAC0000: 		com.google.android.gms.common.api.GoogleApiClient.ConnectionCallbacks,
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): javac.exe error JAVAC0000:
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(9,45): javac.exe error JAVAC0000:  error: cannot find symbol
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(9,45): javac.exe error JAVAC0000: 		com.google.android.gms.common.api.internal.ConnectionCallbacks
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(9,45): javac.exe error JAVAC0000:   symbol:   class ConnectionCallbacks
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(9,45): javac.exe error JAVAC0000:   location: package com.google.android.gms.common.api.internal
1>obj\Debug\net7.0-android33.0\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(9,45): javac.exe error JAVAC0000:

```

I haven't added any code at all to the sample project, just set the .NET version to 7, and the Supported OS Version to 33.0 in the Project Properties.

I'm sure I'm missing something simple, or not using the Nuget Package in the way it is designed... but I can't work out what I'm doing wrong. When I look at the git repo for the parent project (StripeTerminal) I can see that the Envoc.Stripe.Terminal.csproj project is also referencing Envoc.Stripe.Terminal.Android version 2.19.3, and not the latest one, so I'm not sure how to go about referencing the bindings that use the latest Stripe Terminal SDK (3.x)

Thanks for your help... I really appreciate these bindings being made public.

Please let me know if you need any more details.

Chris

**Comment by chris-oswald** [comment]
@christhwaites - Try adding these in your project file

<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" ExcludeAssets="build;buildTransitive">
    <Version>9999.0.0</Version>
</PackageReference>
<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.6.2.1" />
<PackageReference Include="Xamarin.Google.Android.Material" Version="1.10.0" />
<PackageReference Include="Xamarin.GooglePlayServices.Location" Version="121.0.1.4" />
<PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.2" />
<PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.2" />-

**Comment by christhwaites** [comment]
Brilliant!! Thank you so much. Got my project compiling with Stripe v3.x. Thanks.
